Library System/Controllers/AuthorController.cs
using AutoMapper;
using Business.Contracts;
using Business.DTOs;
using Business.Services.Contracts;
using Common.Exceptions;
using Library_System.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Library_System.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService authorService;
        private readonly IMapper mapper;

        public AuthorController(IAuthorService _authorService, IMapper mapper)
        {
            authorService = _authorService;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var authorsList = await authorService.GetAllAuthorsAsync();
            var authorViewModels = mapper.Map<List<GetAuthorViewModel>>(authorsList);

            return View(authorViewModels);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create( AddAuthorViewModel author)
        {
            try
            {
                AuthorDTO authorDTO = mapper.Map<AuthorDTO>(author);
                await authorService.CreateAuthorAsync(authorDTO);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(author);
            }

        }
        public async Task<IActionResult> Edit(int id)
        {
            var author = await authorService.GetAuthorByIdAsync(id);
            if (author == null)
            {
                return NotFound($"Author with ID: {id} is not found.");
            }
            AddAuthorViewModel authorViewModel = mapper.Map<AddAuthorViewModel>(author);
            return View("Create", authorViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AddAuthorViewModel author)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Update", author);
                }
                AuthorDTO authorDTO = mapper.Map<AuthorDTO>(author);
                await authorService.UpdateAuthorAsync(author.AuthorId, authorDTO);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel { Type = ex.GetType().Name, ErrorMessage = ex.Message });

            }
        }
        

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await authorService.DeleteAuthorAsync(id);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View("Error", new ErrorViewModel{ Type= ex.GetType().Name, ErrorMessage = ex.Message });
            }
        }
        

        public async Task<IActionResult> Details([FromRoute] int id)
        {
            var author = await authorService.GetAuthorByIdAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            var authorViewModel = mapper.Map<GetAuthorViewModel>(author);
            return View(authorViewModel);
        }

    }
}

Library System/Controllers/BookController.cs
using AutoMapper;
using Business.Contracts;
using Business.DTOs;
using Business.Services.Contracts;
using Common.Exceptions;
using Common.Filtration;
using Data;
using Domain.Enums;
using Library_System.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Services.DTOs;
using System.ComponentModel;

namespace Library_System.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService bookService;
        private readonly IAuthorService authorService;
        private readonly IMapper mapper;
        public BookController(IBookService _bookService, IAuthorService _authorService, IMapper _mapper)
        {
            bookService = _bookService;
            authorService = _authorService;
            mapper = _mapper;
        }
        public async Task<IActionResult> Index()
        {
            List<GetBookDTO> books = await bookService.GetAllBooksAsync();
            List<GetBookViewModel> bookViewModels = mapper.Map<List<GetBookViewModel>>(books);
            return View(bookViewModels);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Genres = Enum.GetValues<Genre>()
                .Cast<Genre>()
                .Select(d => new SelectListItem
                {
                    Text = d.ToString(), 
                    Value = ((int)d).ToString()
                }).ToList();
            List<GetAuthorDto> authors = await authorService.GetAllAuthorsAsync();
            ViewBag.Authors = mapper.Map<List<GetAuthorViewModel>>(authors);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AddBookViewModel book)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Genres = Enum.GetValues<Genre>()
                .Cast<Genre>()
                .Select(d => new SelectListItem
                {
                    Text = d.ToString(),
                    Value = ((int)d).ToString()
                }).ToList();
                List<GetAuthorDto> authors = await authorService.GetAllAuthorsAsync();
                ViewBag.Authors = mapper.Map<List<GetAuthorViewModel>>(authors);
                return View(book);
            }
            AddBookDTO bookDTO = mapper.Map<AddBookDTO>(book);
            await bookService.CreateBookAsync(bookDTO);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Genres = Enum.GetValues<Genre>()
                .Cast<Genre>()
                .Select(d => new SelectListItem
                {
                    Text = d.ToString(),
                    Value = ((int)d).ToString()
                }).ToList();
            List<GetAuthorDto> authors = await authorService.GetAllAuthorsAsync();
            ViewBag.Authors = mapper.Map<List<GetAuthorViewModel>>(authors);
            GetBookDTO? book = await bookService.GetBookByIdAsync(id);
            var bookViewModel = mapper.Map<AddBookViewModel>(book);
            return View("Create", bookViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AddBookViewModel bookViewModel)
        {
            var bookDto = mapper.Map<AddBookDTO>(bookViewModel);
            try
            {
                await bookService.UpdateBookAsync(bookViewModel.BookId, bookDto);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                ViewBag.Genres = Enum.GetValues<Genre>()
                .Cast<Genre>()
                .Select(d => new SelectListItem
                {
                    Text = d.ToString(),
                    Value = ((int)d).ToString()
                }).ToList();
                List<GetAuthorDto> authors = await authorService.GetAllAuthorsAsync();
                ViewBag.Authors = mapper.Map<List<GetAuthorViewModel>>(authors);
                return View("Create", bookViewModel);
            }

        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await bookService.DeleteBookAsync(id);
                TempData["success"] = "Book Deleted Successfully";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel { Type= ex.GetType().Name, ErrorMessage = ex.Message });
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            GetBookDTO? book = await bookService.GetBookByIdAsync(id);
            if(book == null)
            {
                return NotFound();
            }
            var bookViewModel = mapper.Map<GetBookViewModel>(book);
            return PartialView("_BookDetailPartial", bookViewModel);
        }

        public async Task<IActionResult> FilterBooks(BookSearchCriteria searchCriteria)
        {
            return View();
        }
    }
}

Library System/Controllers/BorrowController.cs
using AutoMapper;
using Business.Contracts;
using Business.Services.Contracts;
using Common.Contracts;
using Domain.Entities;
using Library_System.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Services.DTOs;

namespace Library_System.Controllers
{
    public class BorrowController : Controller
    {
        private readonly IBookService bookService;
        private readonly IBorrowService borrowService;
        private readonly IMapper mapper;

        public BorrowController(IBookService _bookService, IBorrowService _borrowService, IMapper _mapper)
        {
            this.bookService = _bookService;
            this.borrowService = _borrowService;
            mapper = _mapper;
        }
        public async Task<IActionResult> Index()
        {
            var books = await bookService.GetAllBooksAsync(); 
            var bookViewModels = mapper.Map<List<GetBookViewModel>>(books);
            return View(bookViewModels);
        }


        public async Task<IActionResult> RequestBorrow()
        {
            var books = await bookService.GetAvailableBooksAsync();
            ViewBag.Books = mapper.Map<List<GetBookViewModel>>(books);
            return View("Create");
        }
        [HttpPost]
        public async Task<IActionResult> RequestBorrow(BorrowingRecord borrowRecord)
        {
            await borrowService.BorrowBookAsync(borrowRecord.BookId, borrowRecord.BorrowDate);
            return RedirectToAction("BorrowList");
        }

        public async Task<IActionResult> BorrowList()
        {
            var records = await borrowService.GetAll();
            return View(records);
        }


        public async Task<IActionResult> ReturnBook()
        {
            var books = await bookService.GetBorrowedBooksAsync();
            ViewBag.Books = mapper.Map<List<GetBookViewModel>>(books);
            return View("Create");
        }

        public async void GetAvailability(int BookId)
        {
            var book = await bookService.GetBookByIdAsync(BookId);
            if(book != null)
                book.IsAvailable = false;
            
            await bookService.UpdateBookAsync(BookId, mapper.Map<AddBookDTO>(book));
        }
    }
}

Library System/Views/Shared/_BookDetailPartial.cshtml
@model GetBookViewModel
<div class="book-details">
    <h4>@Model.BookTitle</h4>
    <p><strong>Genre:</strong> @Model.Genre</p>
    <p><strong>Author:</strong> @Model.AuthorName</p>
</div>

Library System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library_System.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Borrow" asp-action="Index">Borrow Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Library Management System
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>